name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag deus-ex-api:latest
          docker save deus-ex-api:latest > deus-ex-api.tar
          ls -la deus-ex-api.tar  # Debug: verify file exists

      - name: Deploy to Digital Ocean droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          source: "deus-ex-api.tar"
          target: "/root"
          
      - name: Start Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            docker load < /root/deus-ex-api.tar
            docker compose up -d
