name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag deus-ex-api:latest
          docker save deus-ex-api:latest > deus-ex-api.tar

      - name: Deploy to Digital Ocean droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          source: "deus-ex-api.tar,docker-compose.yml"
          target: "/var/www/api"
          
      - name: Start Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            cd /var/www/api
            docker load < deus-ex-api.tar
            docker compose down || true
            docker compose up -d
            rm deus-ex-api.tar  # Cleanup after deployment
